export const AUTH_REQUEST = '@@auth/AUTH_REQUEST';
export const AUTH_SUCCESS = '@@auth/AUTH_SUCCESS';
export const AUTH_FAILURE = '@@auth/AUTH_FAILURE';

export const LOGOUT = '@@auth/LOGOUT';

export const TOKEN_REQUEST = '@@auth/TOKEN_REQUEST';
export const TOKEN_RECEIVED = '@@auth/TOKEN_RECEIVED';
export const TOKEN_FAILURE = '@@auth/TOKEN_FAILURE';

export const PROFILE_GET_REQUEST = '@@profile/PROFILE_REQUEST';
export const PROFILE_GET_SUCCESS = '@@profile/PROFILE_SUCCESS';
export const PROFILE_GET_FAILURE = '@@profile/PROFILE_FAILURE';

export const PROFILE_POST_REQUEST = '@@profile/PROFILE_POST_REQUEST';
export const PROFILE_POST_SUCCESS = '@@profile/PROFILE_POST_SUCCESS';
export const PROFILE_POST_FAILURE = '@@profile/PROFILE_POST_FAILURE';

export const PROFILE_ADD_WORKER_REQUEST = '@@profile/PROFILE_ADD_WORKER_REQUEST';
export const PROFILE_ADD_WORKER_SUCCESS = '@@profile/PROFILE_ADD_WORKER_SUCCESS';
export const PROFILE_ADD_WORKER_FAILURE = '@@profile/PROFILE_ADD_WORKER_FAILURE';

export const PROFILE_DELETE_WORKER_REQUEST = '@@profile/PROFILE_DELETE_WORKER_REQUEST';
export const PROFILE_DELETE_WORKER_SUCCESS = '@@profile/PROFILE_DELETE_WORKER_SUCCESS';
export const PROFILE_DELETE_WORKER_FAILURE = '@@profile/PROFILE_DELETE_WORKER_FAILURE';

